### ISSUE TITLE
Page refresh bug

### ISSUE THREAD

**Issue by ChantelleKerr** [codersforcauses/wadl#267] opened 2023-02-10 05:27 UTC
When refreshing on all pages it routes back to the home page automatically.

**Comment by benvarian** [comment] 2023-02-11 03:19
cannot reproduce, pls show problem

**Comment by NicholasJDavies** [comment] 2023-04-17 04:58
Unsure how to replicate, but issues in the future might fix. Wontfix for now. If it ever pops up in prod we can force logout everyone, and try again.

**Closed by NicholasJDavies** 2023-04-17 04:58 UTC
Labels: backend, bug, wontfix, priority:medium
